// <auto-generated />
using MacroMateApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MacroMateApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250228160938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MacroMateApp.Models.UserGoals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CalorieGoal")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbGoal")
                        .HasColumnType("REAL");

                    b.Property<double>("FatGoal")
                        .HasColumnType("REAL");

                    b.Property<double>("ProteinGoal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
